version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 253490770873.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t internship/ag-registry-test .
      - echo Tagging the Docker image...
      - docker tag internship/ag-registry-test:latest 253490770873.dkr.ecr.us-east-2.amazonaws.com/internship/ag-registry-test:latest
      - echo Build phase complete.

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 253490770873.dkr.ecr.us-east-2.amazonaws.com/internship/ag-registry-test:latest
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  discard-paths: yes


